name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [
      synchronize,
      opened,
      reopened,
      ready_for_review
    ]
jobs:
  tests:
    name: "Tests (Node ${{ matrix.node }}, Hexo ${{ matrix.hexo }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hexo: [ 3, 4, 5, 6 ]
        node: [ 14, 16 ]

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node }}
     - name: Install dependencies
       run: yarn install --frozen-lockfile
     - name: Install tested hexo version
       env:
         HEXO_VERSION: ${{ matrix.hexo }}
       run: yarn add "hexo@${HEXO_VERSION}"
     - name: Run tests
       run: yarn test
